### PR TITLE
augment version from 2.0.0.0 to 2.0.1.0

### PR DESCRIPTION
**Pull request by JohnMcSpedon**
@fredsadaghiani

### CODE REVIEW

**Comment by JohnMcSpedon** [comment]
will follow deploy steps from [dropbox paper internal doc](https://paper.dropbox.com/doc/sift-python-RKoQwsRskF5KijQq1tfRc)

**Comment by fredsadaghiani** [comment]
LGTM

**Comment by JohnMcSpedon** [comment]
thanks!

**Comment by JohnMcSpedon** [comment]
deployed

**Pull request merged**
